#!/bin/bash
#PBS -q normal
#PBS -l nodes=1:ppn=16:native
#PBS -l walltime=00:30:00
#PBS -N pingpong_524288
#PBS -o Out/singlenode_size_524288.out
#PBS -e Log/singlenode_size_524288.out
#PBS -A TG-CCR120040
#PBS -M gregory.petropoulos@colorado.edu
#PBS -m abe
#PBS -V
# Start of user commands - comments start with a hash sign (#)
cd /oasis/scratch/gregp/temp_project/cs_5576/four
mpirun -np 16 -hostfile $PBS_NODEFILE sn_pingpong 524288 100000
